# -*- coding: utf-8 -*-
"""𝒐𝒊𝒃𝒔𝒊𝒑_2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1L6HQdd0XMm3qVmv4C0VsQn3WMkqLqDxb
"""

import numpy as np  #linear algebra 
import pandas as pd  #data processing

df=pd.read_csv("/content/Unemployment in India.csv")

df.head() #returns first 5 entries

df.tail() #returns last 5 entries

df.shape #returns tuple of shape (Rows, columns) of dataframe

df.info() #prints information about the dataframe

#returns numerical description of the data in the dataframe
df.describe()

x = df['Region']  #plotting column 'Region' on x-axis

x

y=df[' Estimated Unemployment Rate (%)'] #plotting column 'Estimated Unemployment Rate (%)' on y-axis
y #print y

df2=df.iloc[:,3]
df2

import plotly.express as px
import matplotlib.pyplot as plt

fg = px.bar(df,x='Region',y=' Estimated Unemployment Rate (%)',color='Region',
            title='Unemploymeny Rate (State Wise) by Bar Graph',template='plotly')
fg.update_layout(xaxis={'categoryorder':'total descending'})
fg.show()

fg = px.box(df,x='Region',y=' Estimated Unemployment Rate (%)',color='Region',
            title='Unemploymeny Rate (Statewise) by Box Plot',template='plotly')
fg.update_layout(xaxis={'categoryorder':'total descending'}) 
fg.show()

fg = px.scatter(df,x='Region',y=' Estimated Unemployment Rate (%)',color='Region',
                title='Unemploymeny Rate (Statewise) by Scatter Plot',template='plotly')
fg.update_layout(xaxis={'categoryorder':'total descending'})
fg.show()

fg = px.histogram(df,x='Region',y=' Estimated Unemployment Rate (%)',color='Region',
                  title='Unemploymeny Rate (Statewise) by Histogram',template='plotly')
fg.update_layout(xaxis={'categoryorder':'total descending'})
fg.show()