# -*- coding: utf-8 -*-
"""𝒐𝒊𝒃𝒔𝒊𝒑_3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jx0MTTBpqF5j7Fh7Fuc07r88cg03TWel
"""

import numpy as np #linear alegebra 
import pandas as pd #data processing
import matplotlib.pyplot as plt #plot graph
import seaborn as sns # data correlation 
from sklearn.linear_model import LinearRegression

data=pd.read_csv('/content/CarPrice.csv') 
data.head() #data analyzing

data.info()#ckecing wheather there are any nul values

data.shape #used for linear regression format---> (cloumns,row)

#to bulid logistic regression model we need to find correlation between each columns for that we use sns package
plt.figure(figsize=(12,8))
sns.heatmap(data.corr(),annot=True) 
plt.title('Correlation between the columns')

#storing independant features in x variable and dependant feature in y variable
x = data.drop(['price','CarName','fueltype','car_ID','aspiration','doornumber','carbody','drivewheel','enginelocation','enginetype','cylindernumber','fuelsystem'], axis=1)
y = data['price'].values

#Spliting data for building model

from sklearn.model_selection import train_test_split as tts
x_train,x_test,y_train,y_test = tts(x,y,test_size=0.25,random_state=42)

#Building Linear Regression model

from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(x_train,y_train)

#Predicting results for x_test input

pred = model.predict(x_test)

#Checking Accuracy of model using mean square error, mean absolute error and r2 score

import sklearn.metrics as metrics
from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score
print("MSE : ",(metrics.mean_squared_error(pred,y_test)))
print("MAE : ",(metrics.mean_absolute_error(pred,y_test)))
print("R2 Score : ",(metrics.r2_score(pred,y_test)))